services:
  db:
    image: postgres:alpine
    ports:
      - "15432:5432"
    hostname: db
    environment:
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_DB: "app"
    volumes:
      - ./postgres-scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app"]
      interval: 2s
      timeout: 3s
      retries: 40
    profiles:
      - cron
      - script-only
      - db-only

  cron-job:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: app:cron-latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
    restart: unless-stopped
    volumes:
      - ./logs:/usr/app/logs
    profiles:
      - cron
  
  script:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    profiles:
      - script-only
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432


volumes:
  postgres-data: {}
  logs: {}
