FROM python:3.12-slim

RUN apt-get update && apt-get install -y cron && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app

COPY /scripts scripts
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY /src src
RUN chmod +x /usr/app/src/main.py

COPY /scripts/crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab

ENTRYPOINT ["/bin/bash", "-c", "printenv > /etc/environment && cron -f"]
